services:
#    lsv_pollen.example:
#        class: Lsv\PollenBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    ext_authentication_handler:
        class: Lsv\PollenBundle\Services\ExtAuthenticationHandler
        parent: lsv.abstract_service

    lsv.abstract_service:
        class: Lsv\PollenBundle\Services\AbstractService
        calls:
            - [setContainer, [@service_container]]
